language: python

python:
  - 3.4

install:
 - pip install -r requirements.txt
 - python setup.py install

script:
 - nosetests

notifications:
webhooks:
  urls:
    - https://webhooks.gitter.im/e/749cb9261532fc563e2e
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false